### ISSUE TITLE
Bootstrap installation

### ISSUE THREAD

**Issue by thierrymarianne** [afup/back-office#34]
Hello @erichard ,

When accessing the following route `/admin/login`,

I've stumbled upon the following error
`An exception has been thrown during the compilation of a template ("Unable to find file "@AfupAdminBundle/Resources/public/vendor/bootstrap-sortable/Contents/bootstrap-sortable.css".") in "AfupAdminBundle::layout.html.twig".`

Is there a command to be executed to have bootstrap installed and made available for `AfupAdminBundle::layout.html.twig`?

**Comment by erichard** [comment]
Hello @thierrymarianne,

The layout rely on the [bootstrap-sortable](https://github.com/drvic10k/bootstrap-sortable) plugin. It seems that the link is broken [here](https://github.com/afup/back-office/tree/master/src/Afup/AdminBundle/Resources/public/vendor). 

Just need to be updated.

**Comment by thierrymarianne** [comment]
Thanks !
