### ISSUE TITLE
Core/Design

### ISSUE THREAD

**Issue by jewome62** [afup/back-office#37]
Alors pour le design, j'ai trois propositions : 
- http://www.cliptheme.com/demo/rapido/
- http://hubancreative.com/projects/templates/presenter/?theme=coco3
- http://bigmedved.ru/orb/

J'ai abandonné braincrafted, pas intéressant je trouve

**Comment by jewome62** [comment]
@thierrymarianne @webaaz

**Comment by thierrymarianne** [comment]
@jerome62, bon à savoir à propos de de braincrafted. 
Pourrais-tu nous expliquer ce qui t'a déplu stp ?

Les thèmes que tu proposes nécessite un travail d'intégration d'entrée de jeu, n'est-ce pas ?

**Comment by jewome62** [comment]
L'installation est compliqué je trouve, et le rendu est comme sur le site de bootstrap, je trouve cela pas très beau

Avec les templates proposés il faudra faire de l intégration mais c est plus du copier coller de code html existant

**Comment by thierrymarianne** [comment]
@jewome62 Ce n'est pas très beau en effet :/

Si l'installation est compliquée, il vaudrait peut être mieux aller à la recherche d'une autre solution ou alors trouver un moyen d'automatiser l'installation. Comme le proposait @erichard, il vaudrait mieux retenir les solutions les plus simples possibles et donc ne pas conserver ce `bundle`, s'il apparaît comme trop difficile à mettre en place.

**Comment by erichard** [comment]
De toute façon les bundles braincrafted et mopabootstrap vont perdre leur intérêt avec Symfony 2.6 qui embarque deux thèmes de formulaire bootstrapé. A voir ici : http://symfony.com/blog/new-in-symfony-2-6-bootstrap-form-theme

**Comment by jewome62** [comment]
Euh je trouve que l'intégration n'est pas compliqué, il suffit de faire les templates de customisation
http://symfony.com/fr/doc/current/cookbook/form/form_customization.html

**Comment by webaaz** [comment]
J'ai une préférence pour le premier (rapido)
Et techniquement peu m'importe ;-)

**Comment by thierrymarianne** [comment]
+1 pour 1) o/
