### ISSUE TITLE
Problème d'antislash dans le titre d'une conférence

### ISSUE THREAD

**Issue by perrick** [afup/back-office#45]
Le titre de la conférence de Manuel Raynaud contient une erreur : TÉLÉTRAVAIL ? C\'EST BON, MANGEZ-EN !
Reste à trouver l'origine du problème...
![img 2016-09-19 a 14 33 34](https://cloud.githubusercontent.com/assets/505024/18632177/69882430-7e76-11e6-8810-1fd10fb03296.png)

**Comment by mikaelrandy** [comment]
@perrick désolé pour le temps de réponse.
Où est-ce que tu as vu cette erreur dans le backoffice ?

**Comment by perrick** [comment]
Je pensais que ma copie écran serait utile ;-) Il y a un bel anti-slash dans le titre de la conférence. Après je suis bien incapable de t'indiquer d'où viendrait le problème : saisie initiale par le conférencier ? transcodage dans la base de données ? reprise à l'affichage ? Bon courage...

**Comment by mikaelrandy** [comment]
@perrick ta capture d'écran m'a surtout inspiré que ça venait du front, et que le soucis n'est plus présent. D'où ma demande de précisions ;)
<img width="986" alt="capture d ecran 2016-10-25 a 09 19 01" src="https://cloud.githubusercontent.com/assets/187703/19687691/7bc970c4-9a94-11e6-8f3b-44e332a13334.png">

Du coup, je pense qu'on peux fermer, right ?

**Comment by perrick** [comment]
Visiblement oui ;-)
